# Generated by Django 4.1 on 2022-08-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
